### PR TITLE
Implement AnyLifetime for floats

### PR DESCRIPTION
**Pull request by pierd**
... to simplify implementation of [floats in starlark-rust](https://github.com/facebookexperimental/starlark-rust/issues/3).

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks! This looks great. I'll land it shortly once it passes some internal tests (but given the diff, that's just a formality)

**Comment by pierd** [comment]
No worries, there's no rush. I've been using a local copy for development.

**Comment by ndmitchell** [comment]
Thanks very much! I suggest I defer on making a release until you've got the Starlark pieces ready, in case you need to do any further Gazebo changes. But let me know once you think you are finished in Gazebo world.

**Comment by pierd** [comment]
@ndmitchell It looks like I'm done in Gazebo world (almost done with float implementation).

**Comment by ndmitchell** [comment]
Thanks! I'll make a release

**Comment by ndmitchell** [comment]
Version 0.4.2 released, and I've bumped Starlark to require the new version

**Pull request closed without merging**
